robo = "champ"
empty = [" ","\t","\n",""]
welcomeGreetings = ["hello", "hey","hii","hiii", "greetings", "sup","what's up"]
callingrobo = [f"Hi {robo}",f"hello {robo}"]
welcomeGreetings1 = ["good morning","good evening","good afternoon"]
welcomeGreetingResponces = ["hi", "hey", "*nods*", "hi there", "hello", "I am glad! You are talking to me"]
exitGreetings = ["exit","bye","byee","byeee","quit","good night","thanks","thank you"]
saveData = ["save","remember","store"]
askData = ["show","tell","show me","tell me"]
updateData = ["change","update","replace"]
askdiff = ["what","what's"]
yes = ["y","s","yes","ya","yeah","okey","hmmm","hmm"]
no = ["no","leave","na","n"]
userCall = ["me","I","mine","my"]
questioncall = ["what ","when ","where ","why ","?"]
questioncall1 = ["how much","how many"]
moodcall = [" happy","Angry","depress","unhappy","boring",""]
options=["sports","campus","faculty","administration","students","workshops","icc","testimonials","others","gallery","contact","ambulance"]
information = ["dean"," address","campus area temporary","Director","Founded","Chairman","website","fullform","campus"
"motto","Mentor","Acronym","Nearest Airport","enrollment"," 550 (2019)",
"Ownership","Total Faculty","Courses Offered","Railway Station","admission","PLACEMENTS","about",
"location","Contact","email","Ambulance","Astronomy Club","Photography Club","Robotics Club","club","mtech","how to go","how to rich","ragging","autonomus","rank 1 IIT"," rank required","required rank"]
imejas = ["cutoff","dharwad","director","fees","future ","holiday","hostel","location","logo","permanent campus","seats"]
teach = ["sandeep","siba","prabhu"]
title = ["ID","Book Name","Author","Number of copies","Price","Issued","Description","Reviews"]
title1 = ["id","book bame","author","number of copies","price","issued","description","reviews"]